package com.drsaina.mars.testnotification.Data.local.db.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doctorUserDaoConfig;
    private final DaoConfig messagesDaoConfig;

    private final DoctorUserDao doctorUserDao;
    private final messagesDao messagesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doctorUserDaoConfig = daoConfigMap.get(DoctorUserDao.class).clone();
        doctorUserDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(messagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        doctorUserDao = new DoctorUserDao(doctorUserDaoConfig, this);
        messagesDao = new messagesDao(messagesDaoConfig, this);

        registerDao(DoctorUser.class, doctorUserDao);
        registerDao(messages.class, messagesDao);
    }
    
    public void clear() {
        doctorUserDaoConfig.getIdentityScope().clear();
        messagesDaoConfig.getIdentityScope().clear();
    }

    public DoctorUserDao getDoctorUserDao() {
        return doctorUserDao;
    }

    public messagesDao getMessagesDao() {
        return messagesDao;
    }

}
