package com.drsaina.mars.testnotification.Data.local.db.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MESSAGES".
 */
public class messages {

    private Long id;
    private String messageQuestionId;
    private String messageId;
    private String messageIdNew;
    private String messageType;
    private String messageState;
    private String messageSender;
    private String messageFileAttach;
    private String messageDateUpload;
    private String messageContent;
    private String userId;
    private Boolean messageFetch;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public messages() {
    }

    public messages(Long id) {
        this.id = id;
    }

    public messages( Long id, String messageQuestionId, String messageId, String messageIdNew, String messageType, String messageState, String messageSender, String messageFileAttach, String messageDateUpload, String messageContent, String userId, Boolean messageFetch) {
        this.id = id;
        this.messageQuestionId = messageQuestionId;
        this.messageId = messageId;
        this.messageIdNew = messageIdNew;
        this.messageType = messageType;
        this.messageState = messageState;
        this.messageSender = messageSender;
        this.messageFileAttach = messageFileAttach;
        this.messageDateUpload = messageDateUpload;
        this.messageContent = messageContent;
        this.userId = userId;
        this.messageFetch = messageFetch;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessageQuestionId() {
        return messageQuestionId;
    }

    public void setMessageQuestionId(String messageQuestionId) {
        this.messageQuestionId = messageQuestionId;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getMessageIdNew() {
        return messageIdNew;
    }

    public void setMessageIdNew(String messageIdNew) {
        this.messageIdNew = messageIdNew;
    }

    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public String getMessageState() {
        return messageState;
    }

    public void setMessageState(String messageState) {
        this.messageState = messageState;
    }

    public String getMessageSender() {
        return messageSender;
    }

    public void setMessageSender(String messageSender) {
        this.messageSender = messageSender;
    }

    public String getMessageFileAttach() {
        return messageFileAttach;
    }

    public void setMessageFileAttach(String messageFileAttach) {
        this.messageFileAttach = messageFileAttach;
    }

    public String getMessageDateUpload() {
        return messageDateUpload;
    }

    public void setMessageDateUpload(String messageDateUpload) {
        this.messageDateUpload = messageDateUpload;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getUserId () {
        return userId;
    }

    public void setUserId ( String userId ) {
        this.userId = userId;
    }

    public Boolean getMessageFetch() {
        return messageFetch;
    }

    public void setMessageFetch(Boolean messageFetch) {
        this.messageFetch = messageFetch;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
